@php
    $ifthenpayFieldName = $ifthenpayFieldName ?? 'ifthenpay_option';
    $ifthenpayIdPrefix = $ifthenpayIdPrefix ?? 'ifthenpay-option';
    $selectedIfthenpayOption = $selectedIfthenpayOption ?? ($ifthenpayData['default_method'] ?? 'CCARD');
    $ifthenpayOptionMeta = [
        'CCARD' => [
            'label' => __('Credit or debit card'),
            'logo' => 'card',
            'description' => __('Easy and simple payment using a credit or debit card. Payment service provided by IfthenPay.'),
        ],
        'MB' => [
            'label' => __('Multibanco'),
            'logo' => 'multibanco',
            'description' => __('Receive a Multibanco reference and finish the payment securely through IfthenPay.'),
        ],
        'MBWAY' => [
            'label' => __('MB WAY'),
            'logo' => 'mbway',
            'description' => __('Approve the payment quickly with MB WAY using the IfthenPay service.'),
        ],
        'PAYSHOP' => [
            'label' => __('Payshop'),
            'logo' => 'payshop',
            'description' => __('Pay later at a Payshop point with the reference generated by IfthenPay.'),
        ],
    ];
@endphp

<div class="ifthenpay-option-list">
    @foreach ($ifthenpayOptions as $optionValue => $optionLabel)
        @php
            $optionMeta = $ifthenpayOptionMeta[$optionValue] ?? [
                'label' => $optionLabel,
                'logo' => 'default',
                'description' => '',
            ];
            $optionId = $ifthenpayIdPrefix . '-' . strtolower($optionValue);
        @endphp
        <label class="checkout-radio-card ifthenpay-option-card {{ $selectedIfthenpayOption == $optionValue ? 'is-selected' : '' }}"
            for="{{ $optionId }}">
            <input class="checkout-radio-input ifthenpay-option-input" type="radio" name="{{ $ifthenpayFieldName }}"
                id="{{ $optionId }}" value="{{ $optionValue }}"
                {{ $selectedIfthenpayOption == $optionValue ? 'checked' : '' }}>
            <span class="checkout-radio-mark"></span>
            <span class="checkout-radio-copy">
                <span class="checkout-radio-title-row">
                    <span class="checkout-radio-title">{{ $optionMeta['label'] }}</span>
                    @if ($optionMeta['logo'] === 'card')
                        <!-- <span class="checkout-radio-logo logo-card" aria-hidden="true"></span> -->
                        <img src="{{ asset('core/public/storage/images/creditcard_banner_and_icon.svg') }}" alt="Credit Card" width="30" height="24" aria-hidden="true">
                    @elseif ($optionMeta['logo'] === 'multibanco')
                     <img src="{{ asset('core/public/storage/images/multibanco_icon.svg') }}" alt="Multibanco" width="30" height="24" aria-hidden="true">
                        <!-- <span class="checkout-radio-logo logo-multibanco" aria-hidden="true">
                            <span class="checkout-radio-logo-text">MB</span>
                        </span> -->
                    @elseif ($optionMeta['logo'] === 'mbway')
                        <!-- <span class="checkout-radio-logo logo-mbway" aria-hidden="true">
                            <span class="checkout-radio-logo-text">MB WAY</span>
                        </span> -->
                        <img src="{{ asset('core/public/storage/images/mbway_icon.svg') }}" alt="MB WAY" width="30" height="24" aria-hidden="true">
                    @elseif ($optionMeta['logo'] === 'payshop')
                        <!-- <span class="checkout-radio-logo logo-payshop" aria-hidden="true">
                            <span class="checkout-radio-logo-text">Payshop</span>
                            <span class="checkout-radio-logo-dotgrid">
                                <span></span><span></span><span></span><span></span>
                                <span></span><span></span><span></span><span></span>
                                <span></span><span></span><span></span><span></span>
                                <span></span><span></span><span></span><span></span>
                            </span>
                        </span> -->
                          <img src="{{ asset('core/public/storage/images/payshop_icon.svg') }}" alt="Payshop" width="30" height="24" aria-hidden="true">
                    @else
                        <span class="checkout-radio-logo" aria-hidden="true">
                            <span class="checkout-radio-logo-text">IFT</span>
                        </span>
                    @endif
                </span>
                <!-- @if (!empty($optionMeta['description']))
                    <span class="checkout-radio-description">{{ $optionMeta['description'] }}</span>
                @endif -->
            </span>
        </label>
    @endforeach
</div>
